kind: Deployment
apiVersion: apps/v1
metadata:
  name: add-deployment
  labels:
    app: add
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
      version: v1
  template:
    metadata:
      labels:
        app: add
        version: v1
    spec:
      containers:
      - name: add-grpc-cont
        image: mahendrakariya/add_grpc:0.0.3
        ports:
        - containerPort: 50051
        env:
        - name: APP_NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: APP_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CONSUL_CLIENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: NODE_HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - curl -XPUT -d '{"Node":"'"`echo $NODE_HOST_NAME|cut -f1 -d .`"'",
                "ServiceID":"'"$APP_NODE_ID"'"}' http://"$CONSUL_CLIENT_HOST":8500/v1/catalog/deregister
                -vvv
      terminationGracePeriodSeconds: 30

