kind: Deployment
apiVersion: apps/v1
metadata:
  name: add-deployment
  labels:
    app: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
      - name: add-grpc-cont
        image: mahendrakariya/add_grpc:0.0.1
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: add-svc
spec:
  selector:
    app: add
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
